# -*- coding: utf-8 -*-
"""createDB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n-ViJbOHv1x1Icn8BobHXPIFsol9fN8i
"""

import pandas as pd
import sqlite3

def create_and_populate_database():
    # Load Excel files
    participants = pd.read_excel('participants.xlsx')
    projects = pd.read_excel('projects.xlsx')
    countries = pd.read_excel('countries.xlsx')

    # Connect to SQLite database
    conn = sqlite3.connect('ecsel_database.db')
    cursor = conn.cursor()

    # Create tables if they don't exist
    cursor.execute('''CREATE TABLE IF NOT EXISTS Participants (
                      projectID INTEGER,
                      projectAcronym TEXT,
                      organisationID INTEGER,
                      name TEXT,
                      shortName TEXT,
                      activityType TEXT,
                      country TEXT,
                      organizationURL TEXT,
                      role TEXT,
                      ecContribution REAL
                      )''')
    cursor.execute('''CREATE TABLE IF NOT EXISTS Projects (
                      projectID INTEGER,
                      acronym TEXT,
                      title TEXT,
                      totalCost REAL,
                      ecContribution REAL,
                      topics TEXT,
                      fundingScheme TEXT,
                      objective TEXT,
                      year INTEGER
                      )''')
    cursor.execute('''CREATE TABLE IF NOT EXISTS Countries (
                      Country TEXT,
                      Acronym TEXT
                      )''')

    # Populate the tables from dataframes
    participants.to_sql('Participants', conn, if_exists='replace', index=False)
    projects.to_sql('Projects', conn, if_exists='replace', index=False)
    countries.to_sql('Countries', conn, if_exists='replace', index=False)

    conn.close()

# Call the function to create and populate the database
create_and_populate_database()